version: "3.8"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - ./db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - database

  bot:
    depends_on:
      - mongo
    image: "node:20"
    restart: unless-stopped
    user: "node"
    working_dir: /app
    environment:
      TELEGRAM_API_KEY: "" # INSERT YOUR KEY HERE
      MONGO_DB_URL: "mongodb://bot:botpass@mongo:27017/botdb"
    volumes:
      - ./:/app
    command: bash -c " npm install && npm start "
    networks:
      - database

networks:
  database:
    name: database
