services:
  mongo:
    image: mongo:6.0.5
    restart: always
    volumes:
      - ./db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - database

  bot:
    depends_on:
      - mongo
    image: bot
    restart: always
    environment:
      NTBA_FIX_319: any
      TELEGRAM_API_KEY: "" # INSERT YOUR KEY HERE
      MONGO_DB_URL: "mongodb://bot:botpass@mongo:27017/botdb"
    networks:
      - database

networks:
  database:
    name: database
